# .github/workflows/netlify-deploy.yml
name: Deploy React App to Netlify

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js for installing Netlify CLI
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Netlify CLI
      - name: Install Netlify CLI
        run: yarn global add netlify-cli

      # Authenticate and deploy to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}