name: Build and Deploy React App to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build React App and Deploy to Netlify
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js for building React app
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install Netlify CLI globally
      - name: Install Netlify CLI
        run: yarn global add netlify-cli

      # Install dependencies using yarn
      - name: Install dependencies
        run: yarn install

      # Build React app
      - name: Build the app
        run: yarn build

      # Deploy the built app to Netlify
      - name: Deploy to Netlify
        run: netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}